### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by hsw28** [SeanMcGrath/poshmark-autofollow#1]
I think maybe not working... installed under chrome developer tools but my follower count isn't increasing :)

**Comment by SeanMcGrath** [comment]
Yeah, I never finished this. Opted for a non-browser solution, https://github.com/SeanMcGrath/poshmark-crawler

**Comment by hsw28** [comment]
Ah, thanks! Do you just run that from the command line? What exactly does it do-- from a quick glance at the code it seems like it follows everyone your followers are following-- is this correct?
Thanks!

**Comment by SeanMcGrath** [comment]
Yep, you should just be able to install its requirements and execute it like any other python program. You also have to set the poshmark username/password as environment variables POSHMARKUSER and POSHMARKPASS.

Correct, it recursively follows your followers and their followers, etc. Eventually you run into poshmark's rate limiting and captcha, but back when I was using it it was effective

gonna close this issue, and probably delete this half-assed repo, but feel free to ask more questions on the crawler repo.
